"""initial_schema

Revision ID: e2ad2f43ead2
Revises: 
Create Date: 2026-06-07 18:34:43.659149
"""
from alembic import op
import sqlalchemy as sa


revision = 'e2ad2f43ead2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pv_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('nb_slides', sa.Integer(), nullable=True),
    sa.Column('nb_slides_vides', sa.Integer(), nullable=True),
    sa.Column('nb_graphiques_natifs', sa.Integer(), nullable=True),
    sa.Column('nb_images_ocr', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pv_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pv_sessions_id'), ['id'], unique=False)

    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('titre', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('identified_risks', sa.JSON(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pv_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agenda_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agenda_items_id'), ['id'], unique=False)

    op.create_table('meeting_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('agenda_item_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pv_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_notes_id'), ['id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('presence', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pv_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_id'), ['id'], unique=False)

    op.create_table('pv_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=True),
    sa.Column('date_reunion', sa.Date(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('comite_type', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pv_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pv_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pv_drafts_id'), ['id'], unique=False)

    op.create_table('slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('is_empty', sa.Boolean(), nullable=True),
    sa.Column('has_native_chart', sa.Boolean(), nullable=True),
    sa.Column('is_ocr_candidate', sa.Boolean(), nullable=True),
    sa.Column('agenda_item_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pv_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slides_id'), ['id'], unique=False)

    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['pv_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_id'), ['id'], unique=False)

    op.create_table('pv_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.Text(), nullable=True),
    sa.Column('discussion', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('remarques', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_id'], ['pv_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pv_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pv_points_id'), ['id'], unique=False)

    op.create_table('slide_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.Integer(), nullable=False),
    sa.Column('chart_type', sa.String(length=50), nullable=True),
    sa.Column('chart_title', sa.Text(), nullable=True),
    sa.Column('chart_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slide_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slide_charts_id'), ['id'], unique=False)

    op.create_table('slide_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.Integer(), nullable=False),
    sa.Column('table_data', sa.JSON(), nullable=True),
    sa.Column('position_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slide_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slide_tables_id'), ['id'], unique=False)

    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=True),
    sa.Column('translated_content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['pv_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translations_id'), ['id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['pv_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_items_id'), ['id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['pv_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_id'))

    op.drop_table('action_items')
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translations_id'))

    op.drop_table('translations')
    with op.batch_alter_table('slide_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slide_tables_id'))

    op.drop_table('slide_tables')
    with op.batch_alter_table('slide_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slide_charts_id'))

    op.drop_table('slide_charts')
    with op.batch_alter_table('pv_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pv_points_id'))

    op.drop_table('pv_points')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_id'))

    op.drop_table('exports')
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slides_id'))

    op.drop_table('slides')
    with op.batch_alter_table('pv_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pv_drafts_id'))

    op.drop_table('pv_drafts')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_id'))

    op.drop_table('participants')
    with op.batch_alter_table('meeting_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_notes_id'))

    op.drop_table('meeting_notes')
    with op.batch_alter_table('agenda_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agenda_items_id'))

    op.drop_table('agenda_items')
    with op.batch_alter_table('pv_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pv_sessions_id'))

    op.drop_table('pv_sessions')
    # ### end Alembic commands ###
